CS = int(input("Enter CS grade: "))
English = int(input("Enter English grade: "))
Math = int(input("Enter Math grade: "))
History = int(input("Enter Hisotry grade: "))
Science = int(input("Enter Science grade: "))
GPA = ((CS+English+Math+History+Science)/5)
print(GPA)
if GPA >= 90: print("You passed! Your final grade is an A")
else: print("You did well.")
