print("Welcome to the fitness app!")
calories = int(input("How many calories do you consume per day?"))
burned = int(input("How many calories do you burn in a day?"))
left = (calories-burned)
print("This is the calories you have left after an entire day of work!")
print(left)
if left > 0: print("You gained more calories")
else: print("You burned off more calories")
print("If maintaining your current weight is the goal, you should eat as much as you burned off.")
print("I hope you enjoyed this simple app :D! Have a nice day!")
