print("Let's play Silly Sentences!")
name = input("\nEnter a name: ")
adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
food1 = input("Enter a food: ")
food2 = input("Enter another food: ")
noun = input("Enter a noun: ")
place = input("Enter a place: ")
verb = input("Enter a verb: ")
print("\n" + name + " was planning a dream vacation to " + place + ".")
print("She was especially looking forward to trying the local\n cuisine, including " + adjective1 + " " + food1 + " and " + food2 + ".")
print("\n" + name + " will have to practive the language " + adverb + " to\nmake it easier to " + verb + " with people.")
print("\n" + name + " has a long list of sights to see, including the\n" + noun + " museum and the " + adjective2 + " park.")
